## Exercise 4 - Pandas part 1
- Use *earthquake.csv* file from data_files directory in this exercise. **Important:** Edit the original DataFrame throughout this whole notebook!

1 Read the data from the csv file and create a DataFrame from it.

In [68]:
import pandas as pd

eq_data = pd.read_csv("data_files/earthquakes.csv",delimiter=",")

eq_data.head()

,Date,Time,Latitude,Longitude,Type,Depth,Depth Error,Depth Seismic Stations,Magnitude,Magnitude Type,...,Magnitude Seismic Stations,Azimuthal Gap,Horizontal Distance,Horizontal Error,Root Mean Square,ID,Source,Location Source,Magnitude Source,Status
0,01/02/1965,13:44:18,19.246,145.616,Earthquake,131.6,NaN,NaN,6.0,MW,...,NaN,NaN,NaN,NaN,NaN,ISCGEM860706,ISCGEM,ISCGEM,ISCGEM,Automatic
1,01/04/1965,11:29:49,1.863,127.352,Earthquake,80.0,NaN,NaN,5.8,MW,...,NaN,NaN,NaN,NaN,NaN,ISCGEM860737,ISCGEM,ISCGEM,ISCGEM,Automatic
2,01/05/1965,18:05:58,-20.579,-173.972,Earthquake,20.0,NaN,NaN,6.2,MW,...,NaN,NaN,NaN,NaN,NaN,ISCGEM860762,ISCGEM,ISCGEM,ISCGEM,Automatic
3,01/08/1965,18:49:43,-59.076,-23.557,Earthquake,15.0,NaN,NaN,5.8,MW,...,NaN,NaN,NaN,NaN,NaN,ISCGEM860856,ISCGEM,ISCGEM,ISCGEM,Automatic
4,01/09/1965,13:32:50,11.938,126.427,Earthquake,15.0,NaN,NaN,5.8,MW,...,NaN,NaN,NaN,NaN,NaN,ISCGEM860890,ISCGEM,ISCGEM,ISCGEM,Automatic

2 Remove the following columns from the DataFrame: *Magnitude Seismic Stations*, *Azimuthal Gap*, *Horizontal Distance* and *Horizontal Error*.

In [69]:
eq_data.drop(eq_data.iloc[:, 11:15],inplace=True, axis=1)
eq_data.head()

,Date,Time,Latitude,Longitude,Type,Depth,Depth Error,Depth Seismic Stations,Magnitude,Magnitude Type,Magnitude Error,Root Mean Square,ID,Source,Location Source,Magnitude Source,Status
0,01/02/1965,13:44:18,19.246,145.616,Earthquake,131.6,NaN,NaN,6.0,MW,NaN,NaN,ISCGEM860706,ISCGEM,ISCGEM,ISCGEM,Automatic
1,01/04/1965,11:29:49,1.863,127.352,Earthquake,80.0,NaN,NaN,5.8,MW,NaN,NaN,ISCGEM860737,ISCGEM,ISCGEM,ISCGEM,Automatic
2,01/05/1965,18:05:58,-20.579,-173.972,Earthquake,20.0,NaN,NaN,6.2,MW,NaN,NaN,ISCGEM860762,ISCGEM,ISCGEM,ISCGEM,Automatic
3,01/08/1965,18:49:43,-59.076,-23.557,Earthquake,15.0,NaN,NaN,5.8,MW,NaN,NaN,ISCGEM860856,ISCGEM,ISCGEM,ISCGEM,Automatic
4,01/09/1965,13:32:50,11.938,126.427,Earthquake,15.0,NaN,NaN,5.8,MW,NaN,NaN,ISCGEM860890,ISCGEM,ISCGEM,ISCGEM,Automatic

3 Filter data from the DataFrame so that only rows matching the following criteria will be shown:
    - Source must be US
    - Magnitude value must be over 7.8
    - ID value must start with the string "USP0007"

In [84]:
eq_data = eq_data[(eq_data["Source"] == "US") & (eq_data["Magnitude"] >= 7.8) & (eq_data["ID"].str.startswith("USP0007"))]
eq_data
eq_data.dtypes

Date                       object
Time                       object
Latitude                  float64
Longitude                 float64
Type                       object
Depth                     float64
Depth Error               float64
Depth Seismic Stations    float64
Magnitude                 float64
Magnitude Type             object
Magnitude Error           float64
Root Mean Square          float64
ID                         object
Source                     object
Location Source            object
Magnitude Source           object
Status                     object
dtype: object

4 Create a new column to the tenth column position called Grade which will have values from the following formula: ("Magnitude" * "Depth") / "Root Mean Square". Results in this column should be presented with three decimals.

In [93]:
#eq_data.insert(11, column = "Grade", value = eq_data[(eq_data["Magnitude"])*(eq_data["Depth"])/(eq_data["Root Mean Square"])])
#eq_data["Grade"] = eq_data[(eq_data['Magnitude'])*(eq_data['Depth'])/(eq_data['Root Mean Square'])]
eq_data["Grade"] = eq_data['Magnitude']*eq_data['Depth']/eq_data['Root Mean Square']
eq_data
#cols = ['Magnitude', 'Depth', 'Root Mean Square']
#set(eq_data.columns).issuperset(cols)

,Date,Time,Latitude,Longitude,Type,Depth,Depth Error,Depth Seismic Stations,Magnitude,Magnitude Type,Magnitude Error,Root Mean Square,ID,Source,Location Source,Magnitude Source,Status,Grade
12571,07/30/1995,05:11:24,-23.340,-70.294,Earthquake,45.6,NaN,NaN,8.0,MW,NaN,1.1,USP000714T,US,US,HRV,Reviewed,331.636364
12703,10/09/1995,15:35:54,19.055,-104.205,Earthquake,33.0,NaN,NaN,8.0,MW,NaN,1.3,USP00074VC,US,US,HRV,Reviewed,203.076923
12781,12/03/1995,18:01:09,44.663,149.300,Earthquake,33.0,NaN,NaN,7.9,MW,NaN,1.1,USP000782N,US,US,HRV,Reviewed,237.000000
12838,01/01/1996,08:05:11,0.729,119.931,Earthquake,24.0,NaN,NaN,7.9,MW,NaN,1.2,USP00079ZV,US,US,HRV,Reviewed,158.000000
12892,02/17/1996,05:59:31,-0.891,136.952,Earthquake,33.0,NaN,NaN,8.2,MW,NaN,1.3,USP0007D1W,US,US,HRV,Reviewed,208.153846
13059,06/10/1996,04:03:35,51.564,-177.632,Earthquake,33.0,NaN,NaN,7.9,MWC,NaN,0.9,USP0007JCU,US,US,HRV,Reviewed,289.666667
13076,06/17/1996,11:22:19,-7.137,122.589,Earthquake,587.3,NaN,NaN,7.9,MWC,NaN,1.2,USP0007JW8,US,US,HRV,Reviewed,3866.391667